openapi: 3.0.0
info:
  title: Chat App API
  description: API documentation for Chat Application
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Local development server

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token

paths:
  /api/send-otp:
    post:
      tags:
        - Authentication
      summary: Send OTP to email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: "baotran.060103@gmail.com"
      responses:
        '200':
          description: OTP sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "OTP sent successfully"
                  email:
                    type: string
                    example: "baotran.060103@gmail.com"

  /api/verify-otp:
    post:
      tags:
        - Authentication
      summary: Verify OTP code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - otp
              properties:
                email:
                  type: string
                  example: "baotran.060103@gmail.com"
                otp:
                  type: string
                  example: "123456"
      responses:
        '200':
          description: OTP verified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Xác thực thành công"

  /api/register:
    post:
      tags:
        - Authentication
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
                - otp
              properties:
                email:
                  type: string
                  example: "baotran.060103@gmail.com"
                password:
                  type: string
                  example: "1111"
                name:
                  type: string
                  example: "bewchan06"
                profilePic:
                  type: string
                  example: "https://example.com/profile.jpg"
                otp:
                  type: string
                  example: "123456"
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Đăng ký thành công"
                  data:
                    type: object
                    properties:
                      email:
                        type: string
                      name:
                        type: string
                      profilePic:
                        type: string

  /api/login:
    post:
      tags:
        - Authentication
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: "baotran.060103@gmail.com"
                password:
                  type: string
                  example: "1111"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Đăng nhập thành công"
                  token:
                    type: string

  /api/user-details:
    get:
      tags:
        - User
      summary: Get current user details
      security:
        - cookieAuth: []
      responses:
        '200':
          description: User details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  user:
                    type: object
                    properties:
                      email:
                        type: string
                      name:
                        type: string
                      profilePic:
                        type: string

  /api/logout:
    get:
      tags:
        - Authentication
      summary: Logout user
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Đăng xuất thành công"

  /api/forgot-password:
    post:
      tags:
        - Authentication
      summary: Send password reset OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: "baotran.060103@gmail.com"
      responses:
        '200':
          description: OTP sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "OTP đã được gửi đến email của bạn"

  /api/reset-password:
    post:
      tags:
        - Authentication
      summary: Reset password with OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - otp
                - newPassword
              properties:
                email:
                  type: string
                  example: "baotran.060103@gmail.com"
                otp:
                  type: string
                  example: "123456"
                newPassword:
                  type: string
                  example: "newpassword123"
      responses:
        '200':
          description: Password reset successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Mật khẩu đã được cập nhật thành công"